% Generated by MATLAB(R) 9.14 (R2023a) and WLAN Toolbox 3.6 (R2023a).
% Generated on: 29-Nov-2023 16:10:23

%% Generating 802.11b/g (DSSS) waveform
% 802.11b/g (DSSS) configuration
dsssCfg = wlanNonHTConfig('Modulation', 'DSSS', ...
    'DataRate', '1Mbps', ...
    'Preamble', 'Long', ...
    'LockedClocks', true, ...
    'PSDULength', 1000);

numPackets = 1;
% input bit source:
in = randi([0, 1], 1000, 1);

barker = [1; -1; 1; 1; -1; 1; 1; 1; -1; -1; -1];
inv_barker = barker * -1;

% Generation
waveform2 = wlanWaveformGenerator(in, dsssCfg, ...
    'NumPackets', 1);

Fs = wlanSampleRate(dsssCfg); 								 % Specify the sample rate of the waveform in Hz

dbpskdemod = comm.DBPSKDemodulator();

waveform2 = real(waveform2);
modSig2 = dbpskdemod(waveform2);
dbpskdemod = comm.DBPSKDemodulator();
chunkSize = 11;

% Determine the number of chunks
numChunks = ceil(length(waveform2) / chunkSize);
%numChunks = 3;

data2 = zeros(numChunks,1);
disp(numChunks);

% DSSS - barker's 
for i = 1:numChunks
    % Calculate the indices for the current chunk
    startIndex = (i - 1) * chunkSize + 1;
    endIndex = min(i * chunkSize, length(waveform2));

    currentChunk = waveform2(startIndex:endIndex);

    if isequal(currentChunk, barker)
        data2(i) = 1;
    elseif isequal(currentChunk, inv_barker)
        data2(i) = -1;
    else
        disp("Something gone wrong at chunk"); disp(i);
    end
    % Process the current chunk (replace this with your processing code)
    % disp(['Processing Chunk ' num2str(i) ':']);
    % disp(currentChunk);
end


modSig = dbpskdemod(data2);
save("80211data", 'modSig');
%fileID = fopen('binary_data.bin', 'wb');
%fwrite(fileID, modSig, 'ubit1');
%fclose(fileID);